---
title: Learning ggplot
author: ''
date: '2018-06-23'
slug: learning-ggplot
categories: []
tags: []
header:
  caption: ''
  image: ''
---


So, I am learning how to use [ggplot](https://ggplot2.tidyverse.org/reference/). Here is my first attempt using one of my fav datasets: the [Anscombe quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet)

```{r}
library(ggplot2)
library(grid)
library(gridExtra)

data(anscombe)

```


The quartet comprises four datasets that have nearly identical simple descriptive statistics, yet appear very different when graphed.


```{r}

p1<-ggplot(anscombe,aes(x1,y1))+geom_point()+geom_smooth(method="lm",se=FALSE,color="red")+xlim(3,16)
p2<-ggplot(anscombe,aes(x2,y2))+geom_point()+geom_smooth(method="lm",se=FALSE,color="red")+xlim(3,16)
p3<-ggplot(anscombe,aes(x3,y3))+geom_point()+geom_smooth(method="lm",se=FALSE,color="red")+xlim(3,16)
p4<-ggplot(anscombe,aes(x4,y4))+geom_point()+geom_smooth(method="lm",se=FALSE,color="red")+xlim(7,20)

grid.arrange(p1,p2,p3,p4,ncol=2)
```

